# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e-service
    username: postgres
    password: root

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: e-service
    defer-datasource-initialization: true
  sql:
    init:
#      mode: always
      data-locations: classpath:/data/init_data.sql

# JWT properties
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351